global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default value (10s).

# Default set of alerts. This file will be read by the Prometheus
# server on startup and must be present.
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# Конечные точки для сбора информации
scrape_configs:
  # Мониторинг самого себя
  - job_name: 'prometheus'

    # Интервал опроса
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']

  # Мониторинг приложения
  - job_name: 'starlette_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['university_app:8000'] # Replace with the address of your starlette_exporter instance
    metrics_path: /metrics
    scheme: http
