"""test running migrations

Revision ID: 40a589ee3b6c
Revises: 4103952e53a4
Create Date: 2023-05-10 16:39:43.987469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a589ee3b6c'
down_revision = '4103952e53a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
