"""test running migrations

Revision ID: 4103952e53a4
Revises: 8c2f47988f5b
Create Date: 2023-05-10 15:56:16.811072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4103952e53a4'
down_revision = '8c2f47988f5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
