"""test running migrations

Revision ID: 8c2f47988f5b
Revises: b2f49fa6053f
Create Date: 2023-05-10 15:54:57.897613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2f47988f5b'
down_revision = 'b2f49fa6053f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
