"""test running migrations

Revision ID: 8dabc5e4d6f6
Revises: 40a589ee3b6c
Create Date: 2023-05-10 16:46:43.204310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dabc5e4d6f6'
down_revision = '40a589ee3b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
