"""test running migrations

Revision ID: bacf2a14876f
Revises: 8dabc5e4d6f6
Create Date: 2023-05-10 17:28:26.966380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacf2a14876f'
down_revision = '8dabc5e4d6f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
