"""added user roles

Revision ID: ba0f13f608ef
Revises: 6ecbf9a4f62c
Create Date: 2023-05-26 11:18:57.446848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba0f13f608ef'
down_revision = '6ecbf9a4f62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("ARRAY['ROLE_PORTAL_USER', 'ROLE_PORTAL_ADMIN', 'ROLE_PORTAL_SUPERADMIN']")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
